version: '3.7'
services:
  mongodb_container:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis_container:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data_container:/data
volumes:
  mongodb_data_container:
  redis_data_container: